stages:
  - build
  #- deploy


build-job:
  tags:
    - green4
  stage: build
  script:
    - cd ProgramMutator/
    - chmod a+x gradlew
    - ./gradlew --no-daemon build javadoc
  only:
    - master
  artifacts:
    paths:
      - ./build

#deploy-job:
  #tags:
    #- green4
  #stage: deploy
  #script:
  